{
  "openapi": "3.0.1",
  "info": {
    "title": "Project-X",
    "version": "0.1",
    "description": "Project-X"
  },
  "servers": [
    {
      "url": "http://localhost:8080"
    }
  ],
  "paths": {
    "/api/users/login": {
      "post": {
        "name": "Login",
        "summary": "Logs in a user",
        "consumes": [
          "application/json"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "password": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "email": "slavasgod@gmail.com",
                "password": "123123123"
              }
            },
            "required": [
              "username",
              "password"
            ]
          }
        },
        "responses": {
          "200": {
            "description": "Return token",
            "content": {
              "application/json; charset=utf-8": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZW1haWwiOiJ1bml2ZXJzZXp4Y3ZAZ21haWwuY29tIiwiaWF0IjoxNTY4MDIzMjAyLCJleHAiOjE1NjgwMjMyMzh9._apV-RyrCHS0miAE0S9pt-06t6x3Xty-skuIWuLGp_k"
                }
              }
            }
          }
        }
      }
    },
    "/api/users/registration": {
      "post": {
        "name": "Registration",
        "summary": "Register  a user",
        "consumes": [
          "application/json"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "userName": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "confirmPassword": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "email": "universezxcv@gmail.com",
                "password": "123123123",
                "confirmPassword": "123123123",
                "userName": "Artem"
              }
            },
            "required": [
              "username",
              "password"
            ]
          }
        },
        "responses": {
          "200": {
            "description": "Return token",
            "content": {
              "application/json; charset=utf-8": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZW1haWwiOiJ1bml2ZXJzZXp4Y3ZAZ21haWwuY29tIiwiaWF0IjoxNTY4MDIzMjAyLCJleHAiOjE1NjgwMjMyMzh9._apV-RyrCHS0miAE0S9pt-06t6x3Xty-skuIWuLGp_k"
                }
              }
            }
          }
        }
      }
    },
    "/api/users/auth/google": {
      "get": {
        "name": "Google request",
        "summary": "Google request",
        "responses": {
          "200": {
            "description": "Redirect to callback route"
          }
        }
      }
    },
    "/api/auth/users/google/callback": {
      "get": {
        "name": "Callback from google after login",
        "summary": "Google request",
        "responses": {
          "200": {
            "description": "Return token",
            "content": {
              "application/json; charset=utf-8": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZW1haWwiOiJ1bml2ZXJzZXp4Y3ZAZ21haWwuY29tIiwiaWF0IjoxNTY4MDIzMjAyLCJleHAiOjE1NjgwMjMyMzh9._apV-RyrCHS0miAE0S9pt-06t6x3Xty-skuIWuLGp_k"
                }
              }
            }
          }
        }
      }
    },
    "/api/users/auth/linkedin": {
      "get": {
        "name": "Callback from linkein after login",
        "summary": "Linkedin request",
        "responses": {
          "200": {
            "description": "Redirect to callback function"
          }
        }
      }
    },
    "/api/users/auth/linkedin/callback": {
      "get": {
        "name": "Callback from linkein after login",
        "summary": "Linkedin request",
        "responses": {
          "200": {
            "description": "Return token",
            "content": {
              "application/json; charset=utf-8": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZW1haWwiOiJ1bml2ZXJzZXp4Y3ZAZ21haWwuY29tIiwiaWF0IjoxNTY4MDIzMjAyLCJleHAiOjE1NjgwMjMyMzh9._apV-RyrCHS0miAE0S9pt-06t6x3Xty-skuIWuLGp_k"
                }
              }
            }
          }
        }
      }
    },
    "/api/users/change-password/{userId}": {
      "put": {
        "name": "Change password",
        "summary": "Change user password",
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "userId"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "password": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "password": "123123123"
              }
            },
            "required": [
              "password"
            ]
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/users/forgot-password": {
      "post": {
        "name": "Forgot Password",
        "summary": "Send request for changing password",
        "consumes": [
          "application/json"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "email": "admin@admin.com"
              }
            },
            "required": [
              "email"
            ]
          }
        },
        "responses": {
          "200": {
            "description": "Mail sent to the email",
            "content": {
              "application/json; charset=utf-8": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "statusMessage": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            },
            "example": {
              "status": "200",
              "statusMessage": "Ok",
              "message": "Mail sent"
            }
          },
          "400": {
            "description": "Bad request. Wrong validation or User not exist",
            "content": {
              "application/json; charset=utf-8": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            },
            "example": {
              "status": "400",
              "name": "ResetPasswordError",
              "message": "Bad Email"
            }
          }
        }
      }
    },
    "/api/users/reset-password": {
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "name": "Reset Password",
        "summary": "Get params for resetting password",
        "consumes": [
          "application/json"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "password": {
                    "type": "string"
                  },
                  "confirmPassword": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "password": "Admin123456!",
                "confirmPassword": "Admin123456!"
              }
            },
            "required": [
              "password",
              "confirmPassword"
            ]
          }
        },
        "responses": {
          "200": {
            "description": "Password is Updated",
            "content": {
              "application/json; charset=utf-8": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "statusMessage": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            },
            "example": {
              "status": "200",
              "statusMessage": "Ok",
              "message": "Password is updated"
            }
          },
          "400": {
            "description": "Bad request. Wrong validation.",
            "content": {
              "application/json;": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                }
              }
            },
            "example": {
              "status": "400",
              "name": "ResetPasswordError",
              "message": "User not Found"
            }
          }
        }
      }
    },
    "/api/course/preview/{courseId}": {
      "get": {
        "name": "Get Course",
        "summary": "Get Course Preview",
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "courseId"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schemas": {
                  "Course": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer"
                      },
                      "courseName": {
                        "type": "string"
                      },
                      "description": {
                        "type": "string"
                      },
                      "rating": {
                        "type": "integer",
                        "format": "double"
                      },
                      "numberOfEnrolledStudents": {
                        "type": "integer"
                      },
                      "authors": {
                        "type": "string"
                      },
                      "language": {
                        "type": "string"
                      },
                      "createdAt": {
                        "type": "string",
                        "format": "date"
                      },
                      "updatedAt": {
                        "type": "string",
                        "format": "date"
                      },
                      "courseReviews": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "id": {
                              "type": "integer"
                            },
                            "rating": {
                              "type": "integer",
                              "format": "double"
                            },
                            "text": {
                              "type": "string"
                            },
                            "createdAt": {
                              "type": "string",
                              "format": "date"
                            },
                            "updatedAt": {
                              "type": "string",
                              "format": "date"
                            }
                          }
                        }
                      },
                      "profits": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "id": {
                              "type": "integer"
                            },
                            "description": {
                              "type": "string"
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "example": {
                  "id": 1,
                  "courseName": "test",
                  "description": "test",
                  "rating": 3.3,
                  "numberOfEnrolledStudents": 15,
                  "authors": "asdasd",
                  "language": "eu",
                  "createdAt": "2019-10-15T13:38:25.222Z",
                  "updatedAt": "2019-10-15T13:38:25.222Z",
                  "courseReviews": [
                    {
                      "id": 1,
                      "raiting": 4,
                      "text": "sdasdas",
                      "createdAt": "2019-10-15T13:38:25.222Z",
                      "updatedAt": "2019-10-15T13:38:25.222Z"
                    },
                    {
                      "id": 2,
                      "raiting": 3,
                      "text": "dasdasda",
                      "createdAt": "2019-10-15T13:38:25.222Z",
                      "updatedAt": "2019-10-15T13:38:25.222Z"
                    }
                  ],
                  "profits": [
                    {
                      "id": 1,
                      "description": "asdas"
                    },
                    {
                      "id": 2,
                      "description": "dsadasd"
                    },
                    {
                      "id": 3,
                      "description": "asdasd"
                    }
                  ]
                }
              }
            }
          },
          "400": {
            "description": "Course not found."
          }
        }
      }
    },
    "/api/course/carousel-courses/": {
      "get": {
        "name": "Get Courses",
        "summary": "Get Course For Carousel",
        "consumes": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "course": {
                        "title": "type:string",
                        "description": "type:string",
                        "numberOfLessons": "type:integer"
                      }
                    }
                  }
                },
                "example": [
                  {
                    "title": "React",
                    "description": "Some description",
                    "numberOfLessons": 44
                  },
                  {
                    "title": "React",
                    "description": "Some description",
                    "numberOfLessons": 44
                  },
                  {
                    "title": "React",
                    "description": "Some description",
                    "numberOfLessons": 44
                  },
                  {
                    "title": "React",
                    "description": "Some description",
                    "numberOfLessons": 44
                  },
                  {
                    "title": "React",
                    "description": "Some description",
                    "numberOfLessons": 44
                  },
                  {
                    "title": "React",
                    "description": "Some description",
                    "numberOfLessons": 44
                  },
                  {
                    "title": "React",
                    "description": "Some description",
                    "numberOfLessons": 44
                  },
                  {
                    "title": "React",
                    "description": "Some description",
                    "numberOfLessons": 44
                  },
                  {
                    "title": "React",
                    "description": "Some description",
                    "numberOfLessons": 44
                  },
                  {
                    "title": "React",
                    "description": "Some description",
                    "numberOfLessons": 44
                  }
                ]
              }
            }
          },
          "400": {
            "description": "Courses not found."
          }
        }
      }
    },
    "/api/course/subscribe/{courseId}": {
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "name": "Subscribe Course",
        "summary": "Create subscription for Course by User",
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "courseId",
            "description": "course id in DB",
            "required": true,
            "type": "integer",
            "format": "int32"
          }
        ],
        "responses": {
          "200": {
            "description": "Basic Answer",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "integer",
                      "format": "int64"
                    },
                    "statusMessage": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "$ref": "#/definitions/Subscription"
                    }
                  }
                },
                "example": {
                  "status": 201,
                  "statusMessage": "Created",
                  "message": "User has signatured",
                  "data": {
                    "createdAt": "2019-10-29T08:56:53.253Z",
                    "updatedAt": "2019-10-29T08:56:53.253Z",
                    "id": 14,
                    "userId": 2,
                    "courseId": 6
                  }
                }
              }
            }
          },
          "400": {
            "description": "User has already signed"
          },
          "404": {
            "description": "Courses not found."
          }
        }
      }
    },
    "/api/course/subscribe/check/{courseId}": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "name": "Check Subscribe Course",
        "summary": "Check subscription for Course by User",
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "courseId",
            "description": "course id in DB",
            "required": true,
            "type": "integer",
            "format": "int32"
          }
        ],
        "responses": {
          "200": {
            "description": "Basic Answer",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "integer",
                      "format": "int64"
                    },
                    "statusMessage": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "$ref": "#/definitions/Subscription"
                    }
                  }
                },
                "example": {
                  "status": 200,
                  "statusMessage": "Ok",
                  "message": "User has already signed",
                  "data": {
                    "createdAt": "2019-10-29T08:56:53.253Z",
                    "updatedAt": "2019-10-29T08:56:53.253Z",
                    "id": 14,
                    "userId": 2,
                    "courseId": 6
                  }
                }
              }
            }
          },
          "400": {
            "description": "User has already signed"
          },
          "404": {
            "description": "Courses not found."
          }
        }
      }
    },
    "/api/profile/public": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "name": "Get Profile",
        "summary": "Get user profile",
        "consumes": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "User not found."
          }
        }
      },
      "put": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "name": "Update Profile",
        "summary": "Update user profle",
        "consumes": [
          "application/json"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "userName": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  },
                  "twitterLink": {
                    "type": "string"
                  },
                  "linkedInLink": {
                    "type": "string"
                  },
                  "facebookLink": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "userName": "Artsiom",
                "description": "lorem ipsum",
                "twitterLink": "https://twitter.com/",
                "linkedInLink": "https://www.linkedin.com/",
                "facebookLink": "https://www.facebook.com/"
              }
            },
            "required": [
              "userName"
            ]
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "Invalid data",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "userName": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    },
                    "twitterLink": {
                      "type": "string"
                    },
                    "linkedInLink": {
                      "type": "string"
                    },
                    "facebookLink": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "userName": "User name is not allowed to be empty",
                  "description": "Description length must be less than or equal to 255 characters long",
                  "twitterLink": "Twitter link must be a valid uri",
                  "facebookLink": "Facebook link must be a valid uri",
                  "linkedInLink": "Linkedin link must be a valid uri"
                }
              }
            }
          },
          "404": {
            "description": "User not found."
          }
        }
      }
    }
  },
  "definitions": {
    "Subscription": {
      "type": "object",
      "properties": {
        "createdAt": {
          "type": "string",
          "format": "dateTime"
        },
        "updatedAt": {
          "type": "string",
          "format": "dateTime"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "userId": {
          "type": "integer",
          "format": "int64"
        },
        "courseId": {
          "type": "integer",
          "format": "int64"
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "Bearer": {
        "type": "apiKey",
        "name": "Authorization",
        "in": "header"
      }
    }
  },
  "tags": []
}